name: CI
# env:
#   JULIA_NUM_THREADS: 2
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0' # Replace this with the minimum Julia version that your package supports.
          - '1'   # automatically expands to the latest stable 1.x release of Julia
          - '1.6'
          - '1.9'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - os: windows-latest
            version: '1'
            arch: x64
          - os: macOS-latest
            version: '1'
            arch: x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
           JULIA_PKG_SERVER: ""
        ## `allow-failure` not available yet https://github.com/actions/toolkit/issues/399
        #continue-on-error: ${{ matrix.version == 'nightly' }} # comment out to report nightly failures
      - uses: julia-actions/julia-runtest@v1
        env:
           JULIA_PKG_SERVER: ""
        #continue-on-error: ${{ matrix.version == 'nightly' }} # comment out to report nightly failures
      - uses: julia-actions/julia-processcoverage@v1
        #continue-on-error: ${{ matrix.version == 'nightly' }} # comment out to report nightly failures
      - uses: codecov/codecov-action@v1
        #continue-on-error: ${{ matrix.version == 'nightly' }} # comment out to report nightly failures
        with:
          file: lcov.info
